name: master CI/CD

on:
  push:
    branches: [ master ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    
    env:
      DAY_OF_WEEK: Mon/
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ${{ github.WORKSPACE }}/Dakotahstaxes.Com/bin/Release/net5.0/publish/wwwroot/
        server: 66.96.162.135
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}

