name: master CI/CD

on:
  push:
    branches: [ master ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Print Info
      run: echo "$GITHUB_WORKSPACE/Dakotahstaxes.Com/bin/Release/net5.0/publish/wwwroot/"

