name: master CI/CD

on:
  workflow_dispatch:
    inputs:
      deploy_server:
        description: 'The server to deploy to'
        required: false
        default: ${{ secrets.DEPLOY_SERVER }}
      deploy_server_username:
        description: 'The username to use when deploying'
        required: false
        default: ${{ secrets.DEPLOY_USERNAME }}
      deploy_server_password:
        description: 'The password to use when deploying'
        required: false
        default: ${{ secrets.DEPLOY_PASSWORD }}
      deploy_server_port:
        description: 'The port to use when deploying'
        required: false
        default: '21'
  push:
    branches: [ master ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    
    env:
      MAIN_PROJECT: Dakotahstaxes.Com
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build Release
      run: dotnet publish -c Release -r linux-x64
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        local-dir: ${{ github.WORKSPACE }}/${{ env.MAIN_PROJECT }}/bin/Release/net5.0/publish/wwwroot/
        server: ${{ github.event.inputs.deploy_server }}
        username: ${{ github.event.inputs.deploy_server_username }}
        password: ${{ github.event.inputs.deploy_server_password }}
        port: ${{ github.event.inputs.deploy_server_port }}
